name = "KZ73"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["KZ73", "Challenge", "Solution"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
autoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.1"

[[lean_lib]]
name = "KZ73"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
