#!/bin/sh
# Write the statement map STATEMENTS.md from the paper: each numbered statement of main.tex with its Lean
# declarations, or "not formalized", and the scripts that check it with their recorded outputs. They are read from
# the commands \lean, \notlean, \computed and \mapitem that follow the label of each statement in main.tex and print
# nothing in the PDF. The numbers come from main.aux: build the paper first (latexmk -pdf main.tex, in paper/).
# Usage: sh paper/statement-map.sh [--lean] [--write | --check]
#   (no option)  print the table
#   --write      replace the table in STATEMENTS.md
#   --check      exit 1 if STATEMENTS.md holds another table
#   --lean       also check each full declaration name with #check in Lean (needs the built package)
# It fails when a numbered statement other than a question has no entry, when the text names a declaration of the
# namespace KeithZanello that the table does not, when a file, a check of code/impl2/rerun.sh or a recorded output it
# names does not exist, or when the last part of a declaration name is not defined in exactly one file of KZ73/
# (outside KZ73/Challenge.lean).
set -eu
LEAN=0
MODE=
for a in "$@"; do
  case $a in
    --lean) LEAN=1 ;;
    --write | --check) MODE=$a ;;
    *) echo "usage: sh paper/statement-map.sh [--lean] [--write | --check]" >&2; exit 2 ;;
  esac
done
HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(dirname "$HERE")
TEX=$HERE/main.tex
AUX=$HERE/main.aux
MAP=$ROOT/STATEMENTS.md
BEGIN='<!-- statement map: generated by paper/statement-map.sh from paper/main.tex, do not edit -->'
END='<!-- end of the statement map -->'
{ [ -f "$AUX" ] && [ ! "$TEX" -nt "$AUX" ]; } || { echo "statement-map: build the paper first ($AUX is missing or older than main.tex)" >&2; exit 1; }
cd "$ROOT"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

awk -v aux="$AUX" -v decls="$TMP/decls" '
function die(m) { print "statement-map: " m > "/dev/stderr"; failed = 1; exit 1 }
# The content of the brace group that opens at position i of s; sets NEXT to the position after it.
function group(s, i,   d, j, c) {
  if (substr(s, i, 1) != "{") die("line " NR ": { expected after a map command")
  d = 0
  for (j = i; j <= length(s); j++) {
    c = substr(s, j, 1)
    if (c == "{") d++
    else if (c == "}" && --d == 0) { NEXT = j + 1; return substr(s, i + 1, j - i - 1) }
  }
  die("line " NR ": unbalanced braces in a map command (each command stays on one line)")
}
# The file of KZ73/ that defines the declaration d (full name), outside the challenge file.
function file_of(d,   short, cmd, f, n, out) {
  if (d in FILE) return FILE[d]
  short = d; sub(/.*\./, "", short)
  cmd = "grep -rlE \"^[[:space:]]*((private|protected|noncomputable|@\\[[^]]*\\])[[:space:]]+)*(theorem|lemma|def|abbrev|structure|inductive|instance)[[:space:]]+" short "([^A-Za-z0-9_.!?]|$)\" KZ73 --include=*.lean | grep -v \"^KZ73/Challenge.lean$\" | sort"
  n = 0
  while ((cmd | getline f) > 0) { n++; out = f }
  close(cmd)
  if (n != 1) die("declaration " d ": defined in " n " files of KZ73/ (expected 1)")
  FILE[d] = out
  return out
}
function exists(p,   g) {
  g = p; gsub(/<p>/, "*", g)
  return system("for f in " g "; do [ -e \"$f\" ] && exit 0; done; exit 1") == 0
}
# LaTeX of a map command to Markdown: \decl{X} to `X` (and the file of X noted in DECLFILES), \ref to numbers,
# $...$ to GitHub math.
function md(s,   out, i, name, rest) {
  DECLFILES = ""
  while (match(s, /\\decl\{[^}]*\}/)) {
    name = substr(s, RSTART + 6, RLENGTH - 7)
    f = file_of(name); DECLS[name] = 1
    if (index(" " DECLFILES " ", " " f " ") == 0) DECLFILES = DECLFILES (DECLFILES == "" ? "" : " ") f
    s = substr(s, 1, RSTART - 1) "`" name "`" substr(s, RSTART + RLENGTH)
  }
  while (match(s, /\\ref\{[^}]*\}/)) {
    name = substr(s, RSTART + 5, RLENGTH - 6)
    if (!(name in NUM)) die("unknown label " name)
    s = substr(s, 1, RSTART - 1) NUM[name] substr(s, RSTART + RLENGTH)
  }
  gsub(/~/, " ", s); gsub(/\\_/, "_", s)
  out = ""
  while ((i = index(s, "$")) > 0) {
    rest = substr(s, i + 1)
    if (index(rest, "$") == 0) die("line " NR ": unmatched $")
    out = out substr(s, 1, i - 1) "$`" substr(rest, 1, index(rest, "$") - 1) "`$"
    s = substr(rest, index(rest, "$") + 1)
  }
  out = out s
  gsub(/\|/, "\\|", out)
  return out
}
function files_md(list,   a, n, k, o) {
  n = split(list, a, " "); o = ""
  for (k = 1; k <= n; k++) o = o (k > 1 ? ", " : "") "[`" a[k] "`](" a[k] ")"
  return o
}
function add(field, text) { CELL[ROW, field] = CELL[ROW, field] (CELL[ROW, field] == "" ? "" : "; ") text }
BEGIN {
  while ((getline l < aux) > 0)
    if (match(l, /^\\newlabel\{[^}]*\}\{\{[^}]*\}/)) {
      k = l; sub(/^\\newlabel\{/, "", k); sub(/\}.*/, "", k)
      v = l; sub(/^\\newlabel\{[^}]*\}\{\{/, "", v); sub(/\}.*/, "", v)
      NUM[k] = v
    }
  ENVNAME["theorem"] = "Theorem"; ENVNAME["lemma"] = "Lemma"; ENVNAME["proposition"] = "Proposition"
  ENVNAME["corollary"] = "Corollary"; ENVNAME["definition"] = "Definition"; ENVNAME["remark"] = "Remark"
  ENVNAME["question"] = "Question"; ENVNAME["conjB"] = "Conjecture B"
  ROW = 0; ENV = ""
}
{
  line = $0
  gsub(/\\%/, "\001", line); sub(/%.*/, "", line); gsub(/\001/, "\\%", line)
  full = line
  if (match(line, /\\begin\{(theorem|lemma|proposition|corollary|definition|remark|question|conjB)\}/)) {
    ENV = substr(line, RSTART + 7, RLENGTH - 8)
    ROW++; KIND[ROW] = ENV; NAME[ROW] = (ENV == "conjB") ? "Conjecture B" : ""
  }
  if (ENV != "" && NAME[ROW] == "" && match(line, /\\label\{[^}]*\}/)) {
    k = substr(line, RSTART + 7, RLENGTH - 8)
    if (!(k in NUM)) die("label " k " is not in main.aux: rebuild the paper")
    NAME[ROW] = ENVNAME[ENV] " " NUM[k]
  }
  while (match(line, /\\(lean|notlean|computed|mapitem)\{/)) {
    cmd = substr(line, RSTART + 1, RLENGTH - 2)
    a = group(line, RSTART + RLENGTH - 1); rest = substr(line, NEXT)
    if (cmd == "mapitem") { ROW++; KIND[ROW] = "item"; NAME[ROW] = md(a) }
    else if (ROW == 0) die("line " NR ": \\" cmd " before any statement")
    else if (cmd == "lean") { t = md(a); add("lean", t " (" files_md(DECLFILES) ")"); MAPPED[ROW] = 1; FORMAL[ROW] = 1 }
    else if (cmd == "notlean") { t = md(a); add("lean", "not formalized" (t == "" ? "" : "; " t) (DECLFILES == "" ? "" : " (" files_md(DECLFILES) ")")); MAPPED[ROW] = 1; FORMAL[ROW] = 1 }
    else {
      b = group(rest, 1); rest = substr(rest, NEXT)
      c = a; r = ""
      if (index(c, ", ") > 0) { r = substr(c, index(c, ", ") + 2); c = substr(c, 1, index(c, ", ") - 1) }
      nt = split(c, tok, " ")
      for (k = 1; k <= nt; k++) if (tok[k] ~ /\/|\.[a-z]+$/ && !exists(tok[k])) die("no file " tok[k] " (line " NR ")")
      if (tok[2] == "code/impl2/rerun.sh")
        for (k = 3; k <= nt; k++)
          if (!exists("code/impl2/" tok[k] ".out") || system("grep -qE \"(^|[ |])" tok[k] "[|)]\" code/impl2/rerun.sh") != 0)
            die("code/impl2/rerun.sh has no check " tok[k] " (line " NR ")")
      no = split(b, outs, ", "); o = ""
      for (k = 1; k <= no; k++) {
        if (!exists(outs[k])) die("no recorded output " outs[k] " (line " NR ")")
        o = o (k > 1 ? ", " : "") (outs[k] ~ /<p>/ ? "`" outs[k] "`" : "[`" outs[k] "`](" outs[k] ")")
      }
      add("comp", "`" c "`" (r == "" ? "" : ", " md(r)) ": " o)
      MAPPED[ROW] = 1
    }
    line = rest
  }
  # A declaration named in the text of the paper must be in the map.
  l2 = full
  while (match(l2, /KeithZanello\.([A-Za-z0-9_.]|\\_)+/)) {
    d = substr(l2, RSTART, RLENGTH); gsub(/\\_/, "_", d); sub(/\.+$/, "", d); USED[d] = NR; l2 = substr(l2, RSTART + RLENGTH)
  }
  if (ENV != "" && match(full, "\\\\end\\{" ENV "\\}")) ENV = ""
}
END {
  if (failed) exit 1
  for (d in USED) if (!(d in DECLS)) die("the text names " d " (line " USED[d] "), which no map command names")
  for (d in DECLS) print d > decls
  print "| Paper | Lean 4 | Computation: command, recorded output |"
  print "|---|---|---|"
  for (k = 1; k <= ROW; k++) {
    if (!MAPPED[k]) {
      if (KIND[k] == "question") continue
      die((NAME[k] == "" ? "a " KIND[k] : NAME[k]) " has no map command")
    }
    if (KIND[k] != "item" && !FORMAL[k]) die(NAME[k] " has neither \\lean nor \\notlean")
    print "| " NAME[k] " | " CELL[k, "lean"] " | " CELL[k, "comp"] " |"
  }
}' "$TEX" > "$TMP/table"

if [ "$LEAN" = 1 ]; then
  { echo "import KZ73"; sort "$TMP/decls" | sed 's/^/#check @/'; } > "$TMP/Names.lean"
  lake env lean "$TMP/Names.lean" > "$TMP/lean.out" 2>&1 || { cat "$TMP/lean.out" >&2; echo "statement-map: a declaration name does not resolve in Lean" >&2; exit 1; }
  echo "statement-map: the $(wc -l < "$TMP/decls" | tr -d ' ') declarations of the table resolve in Lean" >&2
fi

case "$MODE" in
  "") cat "$TMP/table" ;;
  --write | --check)
    grep -qxF "$BEGIN" "$MAP" && grep -qxF "$END" "$MAP" || { echo "statement-map: no map markers in STATEMENTS.md" >&2; exit 1; }
    awk -v b="$BEGIN" -v e="$END" -v t="$TMP/table" '
      $0 == b { print; while ((getline l < t) > 0) print l; skip = 1; next }
      $0 == e { skip = 0 }
      !skip' "$MAP" > "$TMP/map"
    if [ "$MODE" = --write ]; then cp "$TMP/map" "$MAP"; echo "statement-map: STATEMENTS.md written"
    elif cmp -s "$TMP/map" "$MAP"; then echo "statement-map: STATEMENTS.md is up to date"
    else echo "statement-map: STATEMENTS.md differs from the paper; run sh paper/statement-map.sh --write" >&2; exit 1; fi ;;
esac
