name: Paper

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: paper
      - run: cp paper/main.pdf keith-zanello-73.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: paper
          path: keith-zanello-73.pdf
